var oneWayResultData = {
    "success": true,
    "message": null,
    "code": 200,
    "data": {
        "flightInfos": [
            {
            "setID": 30000007,
            "cacheID": 3500805,
            "cityCodeFrom": "BJS",
            "currencyCode": "CNY",
            "cityCodeTo": "SIN",
            "segmentsLeaveTotalTravelTime": 850,
            "segmentsReturnTotalTravelTime": 0,
            "cityNameFrom": "北京",
            "cityNameTo": "新加坡",
            "totalFareAmountExc": 2080.0000,
            "totalTaxAmountADT": 90.0000,
            "totalFareAmountCHD": 0.0000,
            "totalTaxAmountCHD": 0.0000,
            "isShareFlight": false,
            "isInternationalFlight": true,
            "flightLeaveStartDate": "2016-02-27T01:30:00",
            "flightLeaveEndDate": "2016-02-27T10:20:00",
            "flightReturnStartDate": "0001-01-01T00:00:00",
            "flightReturnEndDate": "0001-01-01T00:00:00",
            "flightLeaveSpacingDay": 0,
            "flightReturnSpacingDay": 0,
            "isStop": false,
            "segmentsLeave": [
                {
                "airportCodeFrom": "PEK",
                "airportCodeTo": "KUL",
                "cityCodeFrom": "BJS",
                "cityCodeTo": "KUL",
                "airportNameFrom": "北京首都机场",
                "airportNameTo": "吉隆坡机场",
                "cityNameFrom": "北京",
                "cityNameTo": "吉隆坡",
                "airCorpCode": "MH",
                "airCorpName": "马来西亚航空公司",
                "flightNo": "361",
                "departDate": "2016-02-27T01:30:00",
                "arriveDate": "2016-02-27T08:00:00",
                "techStopTotal": 0,
                "techStopAirportCode": "",
                "techStopArriveDate": "0001-01-01T00:00:00",
                "techStopDepartDate": "0001-01-01T00:00:00",
                "techStopAirportName": "",
                "cabinClass": "Economy",
                "cabinClassName": "经济舱",
                "planeType": "333",
                "planeName": "空客 A330-300",
                "marketingCarrierCode": "MH",
                "operatingCarrierCode": "MH",
                "termDepart": "T3",
                "termArrive": "T3"
               },
                {
                    "airportCodeFrom": "KUL",
                    "airportCodeTo": "SIN",
                    "cityCodeFrom": "KUL",
                    "cityCodeTo": "SIN",
                    "airportNameFrom": "吉隆坡机场",
                    "airportNameTo": "新加坡机场",
                    "cityNameFrom": "吉隆坡",
                    "cityNameTo": "新加坡",
                    "airCorpCode": "MH",
                    "airCorpName": "马来西亚航空公司",
                    "flightNo": "611",
                    "departDate": "2016-02-27T09:15:00",
                    "arriveDate": "2016-02-27T10:20:00",
                    "techStopTotal": 0,
                    "techStopAirportCode": "",
                    "techStopArriveDate": "0001-01-01T00:00:00",
                    "techStopDepartDate": "0001-01-01T00:00:00",
                    "techStopAirportName": "",
                    "cabinClass": "Economy",
                    "cabinClassName": "经济舱",
                    "planeType": "738",
                    "planeName": "波音737-800",
                    "marketingCarrierCode": "MH",
                    "operatingCarrierCode": "MH",
                    "termDepart": "M",
                    "termArrive": "M"
                },
                {
                    "airportCodeFrom": "KUL",
                    "airportCodeTo": "SIN",
                    "cityCodeFrom": "KUL",
                    "cityCodeTo": "SIN",
                    "airportNameFrom": "吉隆坡机场",
                    "airportNameTo": "新加坡机场",
                    "cityNameFrom": "吉隆坡",
                    "cityNameTo": "新加坡",
                    "airCorpCode": "MH",
                    "airCorpName": "马来西亚航空公司",
                    "flightNo": "611",
                    "departDate": "2016-02-27T09:15:00",
                    "arriveDate": "2016-02-27T10:20:00",
                    "techStopTotal": 0,
                    "techStopAirportCode": "",
                    "techStopArriveDate": "0001-01-01T00:00:00",
                    "techStopDepartDate": "0001-01-01T00:00:00",
                    "techStopAirportName": "",
                    "cabinClass": "Economy",
                    "cabinClassName": "经济舱",
                    "planeType": "738",
                    "planeName": "波音737-800",
                    "marketingCarrierCode": "MH",
                    "operatingCarrierCode": "MH",
                    "termDepart": "M",
                    "termArrive": "M"
                }
            ],
            "segmentsReturn": null,
            "directFlight": 0
         },
            {
            "setID": 30000003,
            "cacheID": 3500805,
            "cityCodeFrom": "BJS",
            "currencyCode": "CNY",
            "cityCodeTo": "SIN",
            "segmentsLeaveTotalTravelTime": 1400,
            "segmentsReturnTotalTravelTime": 0,
            "cityNameFrom": "北京",
            "cityNameTo": "新加坡",
            "totalFareAmountExc": 2575.0000,
            "totalTaxAmountADT": 805.0000,
            "totalFareAmountCHD": 0.0000,
            "totalTaxAmountCHD": 0.0000,
            "isShareFlight": false,
            "isInternationalFlight": true,
            "flightLeaveStartDate": "2016-02-27T05:55:00",
            "flightLeaveEndDate": "2016-02-27T19:55:00",
            "flightReturnStartDate": "0001-01-01T00:00:00",
            "flightReturnEndDate": "0001-01-01T00:00:00",
            "flightLeaveSpacingDay": 0,
            "flightReturnSpacingDay": 0,
            "isStop": false,
            "segmentsLeave": [
                {
                "airportCodeFrom": "PEK",
                "airportCodeTo": "BKK",
                "cityCodeFrom": "BJS",
                "cityCodeTo": "BKK",
                "airportNameFrom": "北京首都机场",
                "airportNameTo": "曼谷机场",
                "cityNameFrom": "北京",
                "cityNameTo": "曼谷",
                "airCorpCode": "TG",
                "airCorpName": "泰国国际航空公司",
                "flightNo": "687",
                "departDate": "2016-02-27T05:55:00",
                "arriveDate": "2016-02-27T10:10:00",
                "techStopTotal": 0,
                "techStopAirportCode": "",
                "techStopArriveDate": "0001-01-01T00:00:00",
                "techStopDepartDate": "0001-01-01T00:00:00",
                "techStopAirportName": "",
                "cabinClass": "Economy",
                "cabinClassName": "经济舱",
                "planeType": "330",
                "planeName": "空客 330-200",
                "marketingCarrierCode": "TG",
                "operatingCarrierCode": "TG",
                "termDepart": "T3",
                "termArrive": "T3"
                },
                {
                "airportCodeFrom": "BKK",
                "airportCodeTo": "SIN",
                "cityCodeFrom": "BKK",
                "cityCodeTo": "SIN",
                "airportNameFrom": "曼谷机场",
                "airportNameTo": "新加坡机场",
                "cityNameFrom": "曼谷",
                "cityNameTo": "新加坡",
                "airCorpCode": "TG",
                "airCorpName": "泰国国际航空公司",
                "flightNo": "409",
                "departDate": "2016-02-27T16:35:00",
                "arriveDate": "2016-02-27T19:55:00",
                "techStopTotal": 0,
                "techStopAirportCode": "",
                "techStopArriveDate": "0001-01-01T00:00:00",
                "techStopDepartDate": "0001-01-01T00:00:00",
                "techStopAirportName": "",
                "cabinClass": "Economy",
                "cabinClassName": "经济舱",
                "planeType": "777",
                "planeName": "波音 777-200/300",
                "marketingCarrierCode": "TG",
                "operatingCarrierCode": "TG",
                "termDepart": "",
                "termArrive": ""
                }
            ],
            "segmentsReturn": null,
            "directFlight": 0
          }
       ],
        "pageNo": 1,
        "pageCount": 1
    }
};

var twoWayResultData = {
    "success": true,
    "message": null,
    "code": 200,
    "data": {
        "flightInfos": [{
            "setID": 30000000,
            "cacheID": 3001022,
            "cityCodeFrom": "BJS",
            "currencyCode": "CNY",
            "cityCodeTo": "SIN",
            "segmentsLeaveTotalTravelTime": 635,
            "segmentsReturnTotalTravelTime": 605,
            "cityNameFrom": "北京",
            "cityNameTo": "新加坡",
            "totalFareAmountExc": 5574.0000,
            "totalTaxAmountADT": 1474.0000,
            "totalFareAmountCHD": 3520.0000,
            "totalTaxAmountCHD": 1384.0000,
            "isShareFlight": false,
            "isInternationalFlight": true,
            "flightLeaveStartDate": "2016-02-22T00:10:00",
            "flightLeaveEndDate": "2016-02-22T06:45:00",
            "flightReturnStartDate": "2016-02-23T01:10:00",
            "flightReturnEndDate": "2016-02-23T07:15:00",
            "flightLeaveSpacingDay": 0,
            "flightReturnSpacingDay": 0,
            "isStop": false,
            "segmentsLeave": [{
                "airportCodeFrom": "PEK",
                "airportCodeTo": "SIN",
                "cityCodeFrom": "BJS",
                "cityCodeTo": "SIN",
                "airportNameFrom": "北京首都机场",
                "airportNameTo": "新加坡机场",
                "cityNameFrom": "北京",
                "cityNameTo": "新加坡",
                "airCorpCode": "SQ",
                "airCorpName": "新加坡航空公司",
                "flightNo": "801",
                "departDate": "2016-02-22T00:10:00",
                "arriveDate": "2016-02-22T06:45:00",
                "techStopTotal": 0,
                "techStopAirportCode": "",
                "techStopArriveDate": "0001-01-01T00:00:00",
                "techStopDepartDate": "0001-01-01T00:00:00",
                "techStopAirportName": "",
                "cabinClass": "Economy",
                "cabinClassName": "经济舱",
                "planeType": "773",
                "planeName": "波音 777-300",
                "marketingCarrierCode": "SQ",
                "operatingCarrierCode": "SQ",
                "operatingCarrierName": "新加坡航空公司",
                "termDepart": "T3",
                "termArrive": "T3"
            }],
            "segmentsReturn": [{
                "airportCodeFrom": "SIN",
                "airportCodeTo": "PEK",
                "cityCodeFrom": "SIN",
                "cityCodeTo": "BJS",
                "airportNameFrom": "新加坡机场",
                "airportNameTo": "北京首都机场",
                "cityNameFrom": "新加坡",
                "cityNameTo": "北京",
                "airCorpCode": "SQ",
                "airCorpName": "新加坡航空公司",
                "flightNo": "800",
                "departDate": "2016-02-23T01:10:00",
                "arriveDate": "2016-02-23T07:15:00",
                "techStopTotal": 0,
                "techStopAirportCode": "",
                "techStopArriveDate": "0001-01-01T00:00:00",
                "techStopDepartDate": "0001-01-01T00:00:00",
                "techStopAirportName": "",
                "cabinClass": "Economy",
                "cabinClassName": "经济舱",
                "planeType": "772",
                "planeName": "波音 777-200",
                "marketingCarrierCode": "SQ",
                "operatingCarrierCode": "SQ",
                "operatingCarrierName": "新加坡航空公司",
                "termDepart": "T3",
                "termArrive": "T3"
            }],
            "directFlight": 1
        }], "pageNo": 1, "pageCount": 1
    }
}